### ISSUE TITLE
Publish latest version?

### ISSUE THREAD

**Issue by srph** [rstacruz/rminimist#1]
Currently I'm trying to setup [hledger-vis](https://github.com/rstacruz/hledger-vis), but fails because [`rminimist@1.1.0`](https://www.npmjs.com/package/rminimist) doesn't seem to be published

```
npm ERR! No compatible version found: rminimist@1.1.0
npm ERR! Valid install targets:
npm ERR! 1.0.1, 1.0.0
```

Also, I checked the npm page:
![screen shot 2016-08-28 at 4 54 17 pm](https://cloud.githubusercontent.com/assets/5093058/18032691/40b0403e-6d40-11e6-954e-f5ac57396beb.png)

Probably just needs the version to be published?

**Comment by rstacruz** [comment]
Neat! You use hledger?

**Comment by srph** [comment]
Yea, but still not getting used to the CLI (weird), so I went looking for a neat web client :D

**Comment by rstacruz** [comment]
That was a typo in hledger-vis; fixed now. Keep in mind hledger-vis isn't really "ready", consider it more of a toy at this point :)
